import 'package:get/get.dart';

// Modèle de données pour un pays
class Country {
  final String name;
  final String code;

  Country({required this.name, required this.code, required String dialCode});
}

// Contrôleur pour gérer les pays
class CountryController extends GetxController {
  // Liste des pays
  var countries = <Country>[
    // Country(name: "Congo", code: "242"),
    // Country(name: "RDC", code: "243"),
    // Country(name: "France", code: "33"),
    // Country(name: "Afghanistan", code: "93"),
    // Country(name: "Albanie", code: "355"),
    // Country(name: "Algérie", code: "213"),
    // Country(name: "Andorre", code: "376"),
    // Country(name: "Angola", code: "244"),
    // Country(name: "Antigua-et-Barbuda", code: "268"),
    // Country(name: "Argentine", code: "54"),
    // Country(name: "Arménie", code: "374"),
    // Country(name: "Australie", code: "61"),
    // Country(name: "Autriche", code: "43"),
    // Country(name: "Azerbaïdjan", code: "994"),
    // Country(name: "Bahamas", code: "242"),
    // Country(name: "Bahreïn", code: "973"),
    // Country(name: "Bangladesh", code: "880"),
    // Country(name: "Barbade", code: "246"),
    // Country(name: "Biélorussie", code: "375"),
    // Country(name: "Belgique", code: "32"),
    // Country(name: "Belize", code: "501"),
    // Country(name: "Bénin", code: "229"),
    // Country(name: "Bhoutan", code: "975"),
    // Country(name: "Bolivie", code: "591"),
    // Country(name: "Bosnie-Herzégovine", code: "387"),
    // Country(name: "Botswana", code: "267"),
    // Country(name: "Brésil", code: "55"),
    // Country(name: "Brunei", code: "673"),
    // Country(name: "Bulgarie", code: "359"),
    // Country(name: "Burkina Faso", code: "226"),
    // Country(name: "Burundi", code: "257"),
    // Country(name: "Cambodge", code: "855"),
    // Country(name: "Cameroun", code: "237"),
    // Country(name: "Canada", code: "1"),
    // Country(name: "Cap-Vert", code: "238"),
    // Country(name: "République centrafricaine", code: "236"),
    // Country(name: "Tchad", code: "235"),
    // Country(name: "Chili", code: "56"),
    // Country(name: "Chine", code: "86"),
    // Country(name: "Colombie", code: "57"),
    // Country(name: "Comores", code: "269"),
    // Country(name: "Costa Rica", code: "506"),
    // Country(name: "Côte d'Ivoire", code: "225"),
    // Country(name: "Croatie", code: "385"),
    // Country(name: "Cuba", code: "53"),
    // Country(name: "Chypre", code: "357"),
    // Country(name: "République tchèque", code: "420"),
    // Country(name: "Danemark", code: "45"),
    // Country(name: "Djibouti", code: "253"),
    // Country(name: "Dominique", code: "767"),
    // Country(name: "République dominicaine", code: "809, 829, 849"),
    // Country(name: "Équateur", code: "593"),
    // Country(name: "Égypte", code: "20"),
    // Country(name: "Salvador", code: "503"),
    // Country(name: "Guinée équatoriale", code: "240"),
    // Country(name: "Érythrée", code: "291"),
    // Country(name: "Estonie", code: "372"),
    // Country(name: "Eswatini", code: "268"),
    // Country(name: "Éthiopie", code: "251"),
    // Country(name: "Fidji", code: "679"),
    // Country(name: "Finlande", code: "358"),
    // Country(name: "Gabon", code: "241"),
    // Country(name: "Gambie", code: "220"),
    // Country(name: "Géorgie", code: "995"),
    // Country(name: "Allemagne", code: "49"),
    // Country(name: "Ghana", code: "233"),
    // Country(name: "Grèce", code: "30"),
    // Country(name: "Grenade", code: "473"),
    // Country(name: "Guatemala", code: "502"),
    // Country(name: "Guinée", code: "224"),
    // Country(name: "Guinée-Bissau", code: "245"),
    // Country(name: "Guyana", code: "592"),
    // Country(name: "Haïti", code: "509"),
    // Country(name: "Honduras", code: "504"),
    // Country(name: "Hongrie", code: "36"),
    // Country(name: "Islande", code: "354"),
    // Country(name: "Inde", code: "91"),
    // Country(name: "Indonésie", code: "62"),
    // Country(name: "Iran", code: "98"),
    // Country(name: "Irak", code: "964"),
    // Country(name: "Irlande", code: "353"),
    // Country(name: "Israël", code: "972"),
    // Country(name: "Italie", code: "39"),
    // Country(name: "Jamaïque", code: "876"),
    // Country(name: "Japon", code: "81"),
    // Country(name: "Jordanie", code: "962"),
    // Country(name: "Kazakhstan", code: "7"),
    // Country(name: "Kenya", code: "254"),
    // Country(name: "Kiribati", code: "686"),
    // Country(name: "Corée du Nord", code: "850"),
    // Country(name: "Corée du Sud", code: "82"),
    // Country(name: "Koweït", code: "965"),
    // Country(name: "Kirghizistan", code: "996"),
    // Country(name: "Laos", code: "856"),
    // Country(name: "Lettonie", code: "371"),
    // Country(name: "Liban", code: "961"),
    // Country(name: "Lesotho", code: "266"),
    // Country(name: "Liberia", code: "231"),
    // Country(name: "Libye", code: "218"),
    // Country(name: "Liechtenstein", code: "423"),
    // Country(name: "Lituanie", code: "370"),
    // Country(name: "Luxembourg", code: "352"),
    // Country(name: "Madagascar", code: "261"),
    // Country(name: "Malawi", code: "265"),
    // Country(name: "Malaisie", code: "60"),
    // Country(name: "Maldives", code: "960"),
    // Country(name: "Mali", code: "223"),
    // Country(name: "Malte", code: "356"),
    // Country(name: "Îles Marshall", code: "692"),
    // Country(name: "Mauritanie", code: "222"),
    // Country(name: "Maurice", code: "230"),
    // Country(name: "Mexique", code: "52"),
    // Country(name: "Micronésie", code: "691"),
    // Country(name: "Moldavie", code: "373"),
    // Country(name: "Monaco", code: "377"),
    // Country(name: "Mongolie", code: "976"),
    // Country(name: "Monténégro", code: "382"),
    // Country(name: "Maroc", code: "212"),
    // Country(name: "Mozambique", code: "258"),
    // Country(name: "Myanmar (Birmanie)", code: "95"),
    // Country(name: "Namibie", code: "264"),
    // Country(name: "Nauru", code: "674"),
    // Country(name: "Népal", code: "977"),
    // Country(name: "Pays-Bas", code: "31"),
    // Country(name: "Nouvelle-Zélande", code: "64"),
    // Country(name: "Nicaragua", code: "505"),
    // Country(name: "Niger", code: "227"),
    // Country(name: "Nigéria", code: "234"),
    // Country(name: "Macédoine du Nord", code: "389"),
    // Country(name: "Norvège", code: "47"),
    // Country(name: "Oman", code: "968"),
    // Country(name: "Pakistan", code: "92"),
    // Country(name: "Palaos", code: "680"),
    // Country(name: "Panama", code: "507"),
    // Country(name: "Papouasie-Nouvelle-Guinée", code: "675"),
    // Country(name: "Paraguay", code: "595"),
    // Country(name: "Pérou", code: "51"),
    // Country(name: "Philippines", code: "63"),
    // Country(name: "Pologne", code: "48"),
    // Country(name: "Portugal", code: "351"),
    // Country(name: "Qatar", code: "974"),
    // Country(name: "Roumanie", code: "40"),
    // Country(name: "Russie", code: "7"),
    // Country(name: "Rwanda", code: "250"),
    // Country(name: "Saint-Christophe-et-Niévès", code: "869"),
    // Country(name: "Sainte-Lucie", code: "758"),
    // Country(name: "Saint-Vincent-et-les-Grenadines", code: "784"),
    // Country(name: "Samoa", code: "685"),
    // Country(name: "Saint-Marin", code: "378"),
    // Country(name: "Sao Tomé-et-Principe", code: "239"),
    // Country(name: "Arabie saoudite", code: "966"),
    // Country(name: "Sénégal", code: "221"),
    // Country(name: "Serbie", code: "381"),
    // Country(name: "Seychelles", code: "248"),
    // Country(name: "Sierra Leone", code: "232"),
    // Country(name: "Singapour", code: "65"),
    // Country(name: "Slovaquie", code: "421"),
    // Country(name: "Slovénie", code: "386"),
    // Country(name: "Îles Salomon", code: "677"),
    // Country(name: "Somalie", code: "252"),
    // Country(name: "Afrique du Sud", code: "27"),
    // Country(name: "Soudan du Sud", code: "211"),
    // Country(name: "Espagne", code: "34"),
    // Country(name: "Sri Lanka", code: "94"),
    // Country(name: "Soudan", code: "249"),
    // Country(name: "Suriname", code: "597"),
    // Country(name: "Suède", code: "46"),
    // Country(name: "Suisse", code: "41"),
    // Country(name: "Syrie", code: "963"),
    // Country(name: "Taiwan", code: "886"),
    // Country(name: "Tadjikistan", code: "992"),
    // Country(name: "Tanzanie", code: "255"),
    // Country(name: "Thaïlande", code: "66"),
    // Country(name: "Timor oriental", code: "670"),
    // Country(name: "Togo", code: "228"),
    // Country(name: "Tonga", code: "676"),
    // Country(name: "Trinité-et-Tobago", code: "868"),
    // Country(name: "Tunisie", code: "216"),
    // Country(name: "Turquie", code: "90"),
    // Country(name: "Turkménistan", code: "993"),
    // Country(name: "Tuvalu", code: "688"),
    // Country(name: "Ouganda", code: "256"),
    // Country(name: "Ukraine", code: "380"),
    // Country(name: "Émirats arabes unis", code: "971"),
    // Country(name: "Royaume-Uni", code: "44"),
    // Country(name: "États-Unis", code: "1"),
    // Country(name: "Uruguay", code: "598"),
    // Country(name: "Ouzbékistan", code: "998"),
    // Country(name: "Vanuatu", code: "678"),
    // Country(name: "Vatican", code: "39 06"),
    // Country(name: "Venezuela", code: "58"),
    // Country(name: "Vietnam", code: "84"),
    // Country(name: "Yémen", code: "967"),
    // Country(name: "Zambie", code: "260"),
    // Country(name: "Zimbabwe", code: "263"),
  ].obs;

  // Pays sélectionné
  var selectedCountry = Rx<Country?>(null);

  // Méthode pour sélectionner un pays
    void setSelectedCountry(Country country) {
    selectedCountry.value = country;
  }
}

// Initialisation du contrôleur
final CountryController countryController = Get.put(CountryController());
