import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'Paramètre de configuration': 'configuration parameter',
          'Modifier mon Profil': 'Edit my Profile',
          'Reinitialiser le code PIN': 'Reset the PIN code',
          "Changer langue de l'application": 'Change application language',
          "Protection de l'application": "Application Protection",
          'Protection avec Face Id':"Protection with Face ID",
          "Condition d'utilisation":"Terms of Use",
          'Nous contacter': 'Contact Us',
          'A propos': 'About',
          'Site web': 'Website',
          'Deconnexion': 'Logout',
          'Version 3.0': 'Version 3.0',
          'configuration': 'configuration',
          'Wallet': 'Wallet',
          'IDENTIFIANT': 'Identifier',
          'Votre empreinte digital': 'Your fingerprin',
          "Activer la sécurité avec l'empreinte digital": 'Enable security with fingerprint',
          'Application déverrouillée': 'Bienvenido',
          'Operation': 'Operation',
          'Accueil': 'Home',
          'Mes Cartes': 'My Cards',
          'client to client': 'Bienvenido',
          'Retrait': 'Withdrawal',
           "Effectuer vos opérations":"Perform your operations",
          'Virement CEMAC': 'CEMAC Transfer',
          'Paiement de facture': 'Bill Payment',
          "Transfert d'argent vers un autre compte": "Money Transfer to another account",
          'Achat de crédit (MTN,Airtel)': 'Credit Purchase (MTN, Airtel)',
          'Mes points': 'My Points',
          'Support Technique': 'Technical Support',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'change_language': 'Change Language',
          'language_english': 'English',
          'language_french': 'French',
          'language_spanish': 'Spanish',
        },
        'fr': {
          'Paramètre de configuration': 'paramètre de configuration',
          'Modifier mon Profil': 'Modifier mon Profil',
          'Reinitialiser le code PIN': 'Reinitialiser le code PIN',
          "Changer langue de l'application": "langue de l'application",
          "Protection de l'application": "Protection de l'application",
          'Protection avec Face Id':'Protection avec Face id',
           "Condition d'utilisation": "Condition General D'utilisation",
          'Nous contacter': 'Nous contacter',
          'A propos': 'A propos',
          'Site web': 'Site web',
          'Deconnexion': 'Deconnexion',
          'Version 3.0': 'Version 3.0',
          'configuration': 'configuration',
          'Wallet': 'Wallet',
          'IDENTIFIANT': 'IDENTIFIANT',
          'Votre empreinte digital': 'Votre empreinte digital',
          'Application déverrouillée': 'Application déverrouillée',
          'Operation': 'Operation',
          'Accueil': 'Accueil',
          'Mes Cartes': 'Mes Cartes',
          'Retrait': 'Retrait',
          'client to client': 'client to client',
          "Effectuer vos opérations":"Effectuer vos opérations",
          'Virement CEMAC': 'Virement CEMAC',
          'Paiement de facture': 'Paiement de facture',
          "Transfert d'argent vers un autre compte": "Transfert d'argent vers un autre compte",
          'Achat de crédit (MTN,Airtel)': 'Achat de crédit (MTN,Airtel',
          'Mes points': 'Mes points',
          'Support Technique': 'Support Technique',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenue',
          'change_language': 'Changer la Langue',
          'language_english': 'Anglais',
          'language_french': 'Français',
          'language_spanish': 'Espagnol',
        },
        'es': {
          'paramètre de configuration': 'parámetro de configuración',
          'Modifier mon Profil': 'Modificar mi Perfil',
          'Reinitialiser le code PIN': 'Reiniciar el código PIN',
          "Changer langue de l'application": 'Cambiar el idioma de la aplicación',
          "Protection de l'application": 'Protección de la aplicación',
          'Protection avec Face Id': 'Protección con Face ID',
          "Condition d'utilisation": 'Términos de uso',
          'Nous contacter': 'Contáctanos',
          'A propos': 'Acerca de',
          'Site web': 'Sitio web',
          'Deconnexion': 'Cerrar',
          'Version 3.0': 'Versión 3.0',
          'configuration': 'Configuración',
          'Wallet': 'Billetera',
          'IDENTIFIANT': 'Identificador',
          'Votre empreinte digital': 'Tu huella digital',
          "Activer la sécurité avec l'empreinte digital": 'Activar la seguridad con la huella digital',
          'Application déverrouillée': 'Aplicación desbloqueada',
          'Operation': 'Operación',
          'Accueil': 'Inicio',
          'Mes Cartes': 'Mis Tarjetas',
          'Retrait': 'Retiro',
          'client to client': 'cliente a cliente',
           "Effectuer vos opérations":"Realizar sus operaciones",
          'Virement CEMAC': 'Transferencia CEMAC',
          'Paiement de facture': 'Pago de facturas',
          "Transfert d'argent vers un autre compte": "Transferencia de dinero a otra cuenta",
          'Achat de crédit (MTN,Airtel)': 'Compra de crédito (MTN, Airtel)',
          'Mes points': 'My Points',
          'Support Technique': 'Technical Support',
          '': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'welcome': 'Bienvenido',
          'change_language': 'Cambiar Idioma',
          'language_english': 'Inglés',
          'language_french': 'Francés',
          'language_spanish': 'Español',
        },
      };
}