// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCowLka9Ns7ye1i12g7o6rdkjcIWsSrSfA',
    appId: '1:555044626923:web:d8ab65cb575daabce379ae',
    messagingSenderId: '555044626923',
    projectId: 'onyfast-cd56d',
    authDomain: 'onyfast-cd56d.firebaseapp.com',
    storageBucket: 'onyfast-cd56d.firebasestorage.app',
    measurementId: 'G-MSNNC4LT5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGJI8a_E0ODjVinMbQd8hpNO0vE4VZaJA',
    appId: '1:555044626923:android:577a09116c264f6de379ae',
    messagingSenderId: '555044626923',
    projectId: 'onyfast-cd56d',
    storageBucket: 'onyfast-cd56d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSPkhROlN5cjcFNoL0G8NRiEb2D4UGoQE',
    appId: '1:555044626923:ios:43597bad1bb6719ee379ae',
    messagingSenderId: '555044626923',
    projectId: 'onyfast-cd56d',
    storageBucket: 'onyfast-cd56d.firebasestorage.app',
    iosBundleId: 'com.onyfast.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSPkhROlN5cjcFNoL0G8NRiEb2D4UGoQE',
    appId: '1:555044626923:ios:43597bad1bb6719ee379ae',
    messagingSenderId: '555044626923',
    projectId: 'onyfast-cd56d',
    storageBucket: 'onyfast-cd56d.firebasestorage.app',
    iosBundleId: 'com.onyfast.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCowLka9Ns7ye1i12g7o6rdkjcIWsSrSfA',
    appId: '1:555044626923:web:e358d4ad0c03268ce379ae',
    messagingSenderId: '555044626923',
    projectId: 'onyfast-cd56d',
    authDomain: 'onyfast-cd56d.firebaseapp.com',
    storageBucket: 'onyfast-cd56d.firebasestorage.app',
    measurementId: 'G-5F28Q2RLMW',
  );
}
