class Country {
  final String name;
  final String alpha2Code;
  final String alpha3Code;
  final String emoji;

  Country({
    required this.name,
    required this.alpha2Code,
    required this.alpha3Code,
    required this.emoji,
  });
}

final List<Country> allCountries = [
  Country(name: 'Afghanistan', alpha2Code: 'AF', alpha3Code: 'AFG', emoji: '🇦🇫'),
  Country(name: 'Albania', alpha2Code: 'AL', alpha3Code: 'ALB', emoji: '🇦🇱'),
  Country(name: 'Algeria', alpha2Code: 'DZ', alpha3Code: 'DZA', emoji: '🇩🇿'),
  Country(name: 'Andorra', alpha2Code: 'AD', alpha3Code: 'AND', emoji: '🇦🇩'),
  Country(name: 'Angola', alpha2Code: 'AO', alpha3Code: 'AGO', emoji: '🇦🇴'),
  Country(name: 'Antigua and Barbuda', alpha2Code: 'AG', alpha3Code: 'ATG', emoji: '🇦🇬'),
  Country(name: 'Argentina', alpha2Code: 'AR', alpha3Code: 'ARG', emoji: '🇦🇷'),
  Country(name: 'Armenia', alpha2Code: 'AM', alpha3Code: 'ARM', emoji: '🇦🇲'),
  Country(name: 'Australia', alpha2Code: 'AU', alpha3Code: 'AUS', emoji: '🇦🇺'),
  Country(name: 'Austria', alpha2Code: 'AT', alpha3Code: 'AUT', emoji: '🇦🇹'),
  Country(name: 'Azerbaijan', alpha2Code: 'AZ', alpha3Code: 'AZE', emoji: '🇦🇿'),
  Country(name: 'Bahamas', alpha2Code: 'BS', alpha3Code: 'BHS', emoji: '🇧🇸'),
  Country(name: 'Bahrain', alpha2Code: 'BH', alpha3Code: 'BHR', emoji: '🇧🇭'),
  Country(name: 'Bangladesh', alpha2Code: 'BD', alpha3Code: 'BGD', emoji: '🇧🇩'),
  Country(name: 'Barbados', alpha2Code: 'BB', alpha3Code: 'BRB', emoji: '🇧🇧'),
  Country(name: 'Belarus', alpha2Code: 'BY', alpha3Code: 'BLR', emoji: '🇧🇾'),
  Country(name: 'Belgium', alpha2Code: 'BE', alpha3Code: 'BEL', emoji: '🇧🇪'),
  Country(name: 'Belize', alpha2Code: 'BZ', alpha3Code: 'BLZ', emoji: '🇧🇿'),
  Country(name: 'Benin', alpha2Code: 'BJ', alpha3Code: 'BEN', emoji: '🇧🇯'),
  Country(name: 'Bhutan', alpha2Code: 'BT', alpha3Code: 'BTN', emoji: '🇧🇹'),
  Country(name: 'Bolivia', alpha2Code: 'BO', alpha3Code: 'BOL', emoji: '🇧🇴'),
  Country(name: 'Bosnia and Herzegovina', alpha2Code: 'BA', alpha3Code: 'BIH', emoji: '🇧🇦'),
  Country(name: 'Botswana', alpha2Code: 'BW', alpha3Code: 'BWA', emoji: '🇧🇼'),
  Country(name: 'Brazil', alpha2Code: 'BR', alpha3Code: 'BRA', emoji: '🇧🇷'),
  Country(name: 'Brunei Darussalam', alpha2Code: 'BN', alpha3Code: 'BRN', emoji: '🇧🇳'),
  Country(name: 'Bulgaria', alpha2Code: 'BG', alpha3Code: 'BGR', emoji: '🇧🇬'),
  Country(name: 'Burkina Faso', alpha2Code: 'BF', alpha3Code: 'BFA', emoji: '🇧🇫'),
  Country(name: 'Burundi', alpha2Code: 'BI', alpha3Code: 'BDI', emoji: '🇧🇮'),
  Country(name: 'Cabo Verde', alpha2Code: 'CV', alpha3Code: 'CPV', emoji: '🇨🇻'),
  Country(name: 'Cambodia', alpha2Code: 'KH', alpha3Code: 'KHM', emoji: '🇰🇭'),
  Country(name: 'Cameroon', alpha2Code: 'CM', alpha3Code: 'CMR', emoji: '🇨🇲'),
  Country(name: 'Canada', alpha2Code: 'CA', alpha3Code: 'CAN', emoji: '🇨🇦'),
  Country(name: 'Central African Republic', alpha2Code: 'CF', alpha3Code: 'CAF', emoji: '🇨🇫'),
  Country(name: 'Chad', alpha2Code: 'TD', alpha3Code: 'TCD', emoji: '🇹🇩'),
  Country(name: 'Chile', alpha2Code: 'CL', alpha3Code: 'CHL', emoji: '🇨🇱'),
  Country(name: 'China', alpha2Code: 'CN', alpha3Code: 'CHN', emoji: '🇨🇳'),
  Country(name: 'Colombia', alpha2Code: 'CO', alpha3Code: 'COL', emoji: '🇨🇴'),
  Country(name: 'Comoros', alpha2Code: 'KM', alpha3Code: 'COM', emoji: '🇰🇲'),
  Country(name: 'Congo (Brazzaville)', alpha2Code: 'CG', alpha3Code: 'COG', emoji: '🇨🇬'),
  Country(name: 'Congo (Kinshasa)', alpha2Code: 'CD', alpha3Code: 'COD', emoji: '🇨🇩'),
  Country(name: 'Costa Rica', alpha2Code: 'CR', alpha3Code: 'CRI', emoji: '🇨🇷'),
  Country(name: 'Croatia', alpha2Code: 'HR', alpha3Code: 'HRV', emoji: '🇭🇷'),
  Country(name: 'Cuba', alpha2Code: 'CU', alpha3Code: 'CUB', emoji: '🇨🇺'),
  Country(name: 'Cyprus', alpha2Code: 'CY', alpha3Code: 'CYP', emoji: '🇨🇾'),
  Country(name: 'Czechia', alpha2Code: 'CZ', alpha3Code: 'CZE', emoji: '🇨🇿'),
  Country(name: 'Denmark', alpha2Code: 'DK', alpha3Code: 'DNK', emoji: '🇩🇰'),
  Country(name: 'Djibouti', alpha2Code: 'DJ', alpha3Code: 'DJI', emoji: '🇩🇯'),
  Country(name: 'Dominica', alpha2Code: 'DM', alpha3Code: 'DMA', emoji: '🇩🇲'),
  Country(name: 'Dominican Republic', alpha2Code: 'DO', alpha3Code: 'DOM', emoji: '🇩🇴'),
  Country(name: 'Ecuador', alpha2Code: 'EC', alpha3Code: 'ECU', emoji: '🇪🇨'),
  Country(name: 'Egypt', alpha2Code: 'EG', alpha3Code: 'EGY', emoji: '🇪🇬'),
  Country(name: 'El Salvador', alpha2Code: 'SV', alpha3Code: 'SLV', emoji: '🇸🇻'),
  Country(name: 'Equatorial Guinea', alpha2Code: 'GQ', alpha3Code: 'GNQ', emoji: '🇬🇶'),
  Country(name: 'Eritrea', alpha2Code: 'ER', alpha3Code: 'ERI', emoji: '🇪🇷'),
  Country(name: 'Estonia', alpha2Code: 'EE', alpha3Code: 'EST', emoji: '🇪🇪'),
  Country(name: 'Eswatini', alpha2Code: 'SZ', alpha3Code: 'SWZ', emoji: '🇸🇿'),
  Country(name: 'Ethiopia', alpha2Code: 'ET', alpha3Code: 'ETH', emoji: '🇪🇹'),
  Country(name: 'Fiji', alpha2Code: 'FJ', alpha3Code: 'FJI', emoji: '🇫🇯'),
  Country(name: 'Finland', alpha2Code: 'FI', alpha3Code: 'FIN', emoji: '🇫🇮'),
  Country(name: 'France', alpha2Code: 'FR', alpha3Code: 'FRA', emoji: '🇫🇷'),
  Country(name: 'Gabon', alpha2Code: 'GA', alpha3Code: 'GAB', emoji: '🇬🇦'),
  Country(name: 'Gambia', alpha2Code: 'GM', alpha3Code: 'GMB', emoji: '🇬🇲'),
  Country(name: 'Georgia', alpha2Code: 'GE', alpha3Code: 'GEO', emoji: '🇬🇪'),
  Country(name: 'Germany', alpha2Code: 'DE', alpha3Code: 'DEU', emoji: '🇩🇪'),
  Country(name: 'Ghana', alpha2Code: 'GH', alpha3Code: 'GHA', emoji: '🇬🇭'),
  Country(name: 'Greece', alpha2Code: 'GR', alpha3Code: 'GRC', emoji: '🇬🇷'),
  Country(name: 'Grenada', alpha2Code: 'GD', alpha3Code: 'GRD', emoji: '🇬🇩'),
  Country(name: 'Guatemala', alpha2Code: 'GT', alpha3Code: 'GTM', emoji: '🇬🇹'),
  Country(name: 'Guinea', alpha2Code: 'GN', alpha3Code: 'GIN', emoji: '🇬🇳'),
  Country(name: 'Guinea-Bissau', alpha2Code: 'GW', alpha3Code: 'GNB', emoji: '🇬🇼'),
  Country(name: 'Guyana', alpha2Code: 'GY', alpha3Code: 'GUY', emoji: '🇬🇾'),
  Country(name: 'Haiti', alpha2Code: 'HT', alpha3Code: 'HTI', emoji: '🇭🇹'),
  Country(name: 'Honduras', alpha2Code: 'HN', alpha3Code: 'HND', emoji: '🇭🇳'),
  Country(name: 'Hungary', alpha2Code: 'HU', alpha3Code: 'HUN', emoji: '🇭🇺'),
  Country(name: 'Iceland', alpha2Code: 'IS', alpha3Code: 'ISL', emoji: '🇮🇸'),
  Country(name: 'India', alpha2Code: 'IN', alpha3Code: 'IND', emoji: '🇮🇳'),
  Country(name: 'Indonesia', alpha2Code: 'ID', alpha3Code: 'IDN', emoji: '🇮🇩'),
  Country(name: 'Iran', alpha2Code: 'IR', alpha3Code: 'IRN', emoji: '🇮🇷'),
  Country(name: 'Iraq', alpha2Code: 'IQ', alpha3Code: 'IRQ', emoji: '🇮🇶'),
  Country(name: 'Ireland', alpha2Code: 'IE', alpha3Code: 'IRL', emoji: '🇮🇪'),
  Country(name: 'Israel', alpha2Code: 'IL', alpha3Code: 'ISR', emoji: '🇮🇱'),
  Country(name: 'Italy', alpha2Code: 'IT', alpha3Code: 'ITA', emoji: '🇮🇹'),
  Country(name: 'Jamaica', alpha2Code: 'JM', alpha3Code: 'JAM', emoji: '🇯🇲'),
  Country(name: 'Japan', alpha2Code: 'JP', alpha3Code: 'JPN', emoji: '🇯🇵'),
  Country(name: 'Jordan', alpha2Code: 'JO', alpha3Code: 'JOR', emoji: '🇯🇴'),
  Country(name: 'Kazakhstan', alpha2Code: 'KZ', alpha3Code: 'KAZ', emoji: '🇰🇿'),
  Country(name: 'Kenya', alpha2Code: 'KE', alpha3Code: 'KEN', emoji: '🇰🇪'),
  Country(name: 'Kiribati', alpha2Code: 'KI', alpha3Code: 'KIR', emoji: '🇰🇮'),
  Country(name: 'Kuwait', alpha2Code: 'KW', alpha3Code: 'KWT', emoji: '🇰🇼'),
  Country(name: 'Kyrgyzstan', alpha2Code: 'KG', alpha3Code: 'KGZ', emoji: '🇰🇬'),
  Country(name: 'Laos', alpha2Code: 'LA', alpha3Code: 'LAO', emoji: '🇱🇦'),
  Country(name: 'Latvia', alpha2Code: 'LV', alpha3Code: 'LVA', emoji: '🇱🇻'),
  Country(name: 'Lebanon', alpha2Code: 'LB', alpha3Code: 'LBN', emoji: '🇱🇧'),
  Country(name: 'Lesotho', alpha2Code: 'LS', alpha3Code: 'LSO', emoji: '🇱🇸'),
  Country(name: 'Liberia', alpha2Code: 'LR', alpha3Code: 'LBR', emoji: '🇱🇷'),
  Country(name: 'Libya', alpha2Code: 'LY', alpha3Code: 'LBY', emoji: '🇱🇾'),
  Country(name: 'Liechtenstein', alpha2Code: 'LI', alpha3Code: 'LIE', emoji: '🇱🇮'),
  Country(name: 'Lithuania', alpha2Code: 'LT', alpha3Code: 'LTU', emoji: '🇱🇹'),
  Country(name: 'Luxembourg', alpha2Code: 'LU', alpha3Code: 'LUX', emoji: '🇱🇺'),
  Country(name: 'Madagascar', alpha2Code: 'MG', alpha3Code: 'MDG', emoji: '🇲🇬'),
  Country(name: 'Malawi', alpha2Code: 'MW', alpha3Code: 'MWI', emoji: '🇲🇼'),
  Country(name: 'Malaysia', alpha2Code: 'MY', alpha3Code: 'MYS', emoji: '🇲🇾'),
  Country(name: 'Maldives', alpha2Code: 'MV', alpha3Code: 'MDV', emoji: '🇲🇻'),
  Country(name: 'Mali', alpha2Code: 'ML', alpha3Code: 'MLI', emoji: '🇲🇱'),
  Country(name: 'Malta', alpha2Code: 'MT', alpha3Code: 'MLT', emoji: '🇲🇹'),
  Country(name: 'Marshall Islands', alpha2Code: 'MH', alpha3Code: 'MHL', emoji: '🇲🇭'),
  Country(name: 'Mauritania', alpha2Code: 'MR', alpha3Code: 'MRT', emoji: '🇲🇷'),
  Country(name: 'Mauritius', alpha2Code: 'MU', alpha3Code: 'MUS', emoji: '🇲🇺'),
  Country(name: 'Mexico', alpha2Code: 'MX', alpha3Code: 'MEX', emoji: '🇲🇽'),
  Country(name: 'Micronesia', alpha2Code: 'FM', alpha3Code: 'FSM', emoji: '🇫🇲'),
  Country(name: 'Moldova', alpha2Code: 'MD', alpha3Code: 'MDA', emoji: '🇲🇩'),
  Country(name: 'Monaco', alpha2Code: 'MC', alpha3Code: 'MCO', emoji: '🇲🇨'),
  Country(name: 'Mongolia', alpha2Code: 'MN', alpha3Code: 'MNG', emoji: '🇲🇳'),
  Country(name: 'Montenegro', alpha2Code: 'ME', alpha3Code: 'MNE', emoji: '🇲🇪'),
  Country(name: 'Morocco', alpha2Code: 'MA', alpha3Code: 'MAR', emoji: '🇲🇦'),
  Country(name: 'Mozambique', alpha2Code: 'MZ', alpha3Code: 'MOZ', emoji: '🇲🇿'),
  Country(name: 'Myanmar', alpha2Code: 'MM', alpha3Code: 'MMR', emoji: '🇲🇲'),
  Country(name: 'Namibia', alpha2Code: 'NA', alpha3Code: 'NAM', emoji: '🇳🇦'),
  Country(name: 'Nauru', alpha2Code: 'NR', alpha3Code: 'NRU', emoji: '🇳🇷'),
  Country(name: 'Nepal', alpha2Code: 'NP', alpha3Code: 'NPL', emoji: '🇳🇵'),
  Country(name: 'Netherlands', alpha2Code: 'NL', alpha3Code: 'NLD', emoji: '🇳🇱'),
  Country(name: 'New Zealand', alpha2Code: 'NZ', alpha3Code: 'NZL', emoji: '🇳🇿'),
  Country(name: 'Nicaragua', alpha2Code: 'NI', alpha3Code: 'NIC', emoji: '🇳🇮'),
  Country(name: 'Niger', alpha2Code: 'NE', alpha3Code: 'NER', emoji: '🇳🇪'),
  Country(name: 'Nigeria', alpha2Code: 'NG', alpha3Code: 'NGA', emoji: '🇳🇬'),
  Country(name: 'North Korea', alpha2Code: 'KP', alpha3Code: 'PRK', emoji: '🇰🇵'),
  Country(name: 'North Macedonia', alpha2Code: 'MK', alpha3Code: 'MKD', emoji: '🇲🇰'),
  Country(name: 'Norway', alpha2Code: 'NO', alpha3Code: 'NOR', emoji: '🇳🇴'),
  Country(name: 'Oman', alpha2Code: 'OM', alpha3Code: 'OMN', emoji: '🇴🇲'),
  Country(name: 'Pakistan', alpha2Code: 'PK', alpha3Code: 'PAK', emoji: '🇵🇰'),
  Country(name: 'Palau', alpha2Code: 'PW', alpha3Code: 'PLW', emoji: '🇵🇼'),
  Country(name: 'Palestine State', alpha2Code: 'PS', alpha3Code: 'PSE', emoji: '🇵🇸'),
  Country(name: 'Panama', alpha2Code: 'PA', alpha3Code: 'PAN', emoji: '🇵🇦'),
  Country(name: 'Papua New Guinea', alpha2Code: 'PG', alpha3Code: 'PNG', emoji: '🇵🇬'),
  Country(name: 'Paraguay', alpha2Code: 'PY', alpha3Code: 'PRY', emoji: '🇵🇾'),
  Country(name: 'Peru', alpha2Code: 'PE', alpha3Code: 'PER', emoji: '🇵🇪'),
  Country(name: 'Philippines', alpha2Code: 'PH', alpha3Code: 'PHL', emoji: '🇵🇭'),
  Country(name: 'Poland', alpha2Code: 'PL', alpha3Code: 'POL', emoji: '🇵🇱'),
  Country(name: 'Portugal', alpha2Code: 'PT', alpha3Code: 'PRT', emoji: '🇵🇹'),
  Country(name: 'Qatar', alpha2Code: 'QA', alpha3Code: 'QAT', emoji: '🇶🇦'),
  Country(name: 'Romania', alpha2Code: 'RO', alpha3Code: 'ROU', emoji: '🇷🇴'),
  Country(name: 'Russia', alpha2Code: 'RU', alpha3Code: 'RUS', emoji: '🇷🇺'),
  Country(name: 'Rwanda', alpha2Code: 'RW', alpha3Code: 'RWA', emoji: '🇷🇼'),
  Country(name: 'Saint Kitts and Nevis', alpha2Code: 'KN', alpha3Code: 'KNA', emoji: '🇰🇳'),
  Country(name: 'Saint Lucia', alpha2Code: 'LC', alpha3Code: 'LCA', emoji: '🇱🇨'),
  Country(name: 'Saint Vincent and the Grenadines', alpha2Code: 'VC', alpha3Code: 'VCT', emoji: '🇻🇨'),
  Country(name: 'Samoa', alpha2Code: 'WS', alpha3Code: 'WSM', emoji: '🇼🇸'),
  Country(name: 'San Marino', alpha2Code: 'SM', alpha3Code: 'SMR', emoji: '🇸🇲'),
  Country(name: 'Sao Tome and Principe', alpha2Code: 'ST', alpha3Code: 'STP', emoji: '🇸🇹'),
  Country(name: 'Saudi Arabia', alpha2Code: 'SA', alpha3Code: 'SAU', emoji: '🇸🇦'),
  Country(name: 'Senegal', alpha2Code: 'SN', alpha3Code: 'SEN', emoji: '🇸🇳'),
  Country(name: 'Serbia', alpha2Code: 'RS', alpha3Code: 'SRB', emoji: '🇷🇸'),
  Country(name: 'Seychelles', alpha2Code: 'SC', alpha3Code: 'SYC', emoji: '🇸🇨'),
  Country(name: 'Sierra Leone', alpha2Code: 'SL', alpha3Code: 'SLE', emoji: '🇸🇱'),
  Country(name: 'Singapore', alpha2Code: 'SG', alpha3Code: 'SGP', emoji: '🇸🇬'),
  Country(name: 'Slovakia', alpha2Code: 'SK', alpha3Code: 'SVK', emoji: '🇸🇰'),
  Country(name: 'Slovenia', alpha2Code: 'SI', alpha3Code: 'SVN', emoji: '🇸🇮'),
  Country(name: 'Solomon Islands', alpha2Code: 'SB', alpha3Code: 'SLB', emoji: '🇸🇧'),
  Country(name: 'Somalia', alpha2Code: 'SO', alpha3Code: 'SOM', emoji: '🇸🇴'),
  Country(name: 'South Africa', alpha2Code: 'ZA', alpha3Code: 'ZAF', emoji: '🇿🇦'),
  Country(name: 'South Korea', alpha2Code: 'KR', alpha3Code: 'KOR', emoji: '🇰🇷'),
  Country(name: 'South Sudan', alpha2Code: 'SS', alpha3Code: 'SSD', emoji: '🇸🇸'),
  Country(name: 'Spain', alpha2Code: 'ES', alpha3Code: 'ESP', emoji: '🇪🇸'),
  Country(name: 'Sri Lanka', alpha2Code: 'LK', alpha3Code: 'LKA', emoji: '🇱🇰'),
  Country(name: 'Sudan', alpha2Code: 'SD', alpha3Code: 'SDN', emoji: '🇸🇩'),
  Country(name: 'Suriname', alpha2Code: 'SR', alpha3Code: 'SUR', emoji: '🇸🇷'),
  Country(name: 'Sweden', alpha2Code: 'SE', alpha3Code: 'SWE', emoji: '🇸🇪'),
  Country(name: 'Switzerland', alpha2Code: 'CH', alpha3Code: 'CHE', emoji: '🇨🇭'),
  Country(name: 'Syria', alpha2Code: 'SY', alpha3Code: 'SYR', emoji: '🇸🇾'),
  Country(name: 'Taiwan', alpha2Code: 'TW', alpha3Code: 'TWN', emoji: '🇹🇼'),
  Country(name: 'Tajikistan', alpha2Code: 'TJ', alpha3Code: 'TJK', emoji: '🇹🇯'),
  Country(name: 'Tanzania', alpha2Code: 'TZ', alpha3Code: 'TZA', emoji: '🇹🇿'),
  Country(name: 'Thailand', alpha2Code: 'TH', alpha3Code: 'THA', emoji: '🇹🇭'),
  Country(name: 'Timor-Leste', alpha2Code: 'TL', alpha3Code: 'TLS', emoji: '🇹🇱'),
  Country(name: 'Togo', alpha2Code: 'TG', alpha3Code: 'TGO', emoji: '🇹🇬'),
  Country(name: 'Tonga', alpha2Code: 'TO', alpha3Code: 'TON', emoji: '🇹🇴'),
  Country(name: 'Trinidad and Tobago', alpha2Code: 'TT', alpha3Code: 'TTO', emoji: '🇹🇹'),
  Country(name: 'Tunisia', alpha2Code: 'TN', alpha3Code: 'TUN', emoji: '🇹🇳'),
  Country(name: 'Turkey', alpha2Code: 'TR', alpha3Code: 'TUR', emoji: '🇹🇷'),
  Country(name: 'Turkmenistan', alpha2Code: 'TM', alpha3Code: 'TKM', emoji: '🇹🇲'),
  Country(name: 'Tuvalu', alpha2Code: 'TV', alpha3Code: 'TUV', emoji: '🇹🇻'),
  Country(name: 'Uganda', alpha2Code: 'UG', alpha3Code: 'UGA', emoji: '🇺🇬'),
  Country(name: 'Ukraine', alpha2Code: 'UA', alpha3Code: 'UKR', emoji: '🇺🇦'),
  Country(name: 'United Arab Emirates', alpha2Code: 'AE', alpha3Code: 'ARE', emoji: '🇦🇪'),
  Country(name: 'United Kingdom', alpha2Code: 'GB', alpha3Code: 'GBR', emoji: '🇬🇧'),
  Country(name: 'United States', alpha2Code: 'US', alpha3Code: 'USA', emoji: '🇺🇸'),
  Country(name: 'Uruguay', alpha2Code: 'UY', alpha3Code: 'URY', emoji: '🇺🇾'),
  Country(name: 'Uzbekistan', alpha2Code: 'UZ', alpha3Code: 'UZB', emoji: '🇺🇿'),
  Country(name: 'Vanuatu', alpha2Code: 'VU', alpha3Code: 'VUT', emoji: '🇻🇺'),
  Country(name: 'Vatican City', alpha2Code: 'VA', alpha3Code: 'VAT', emoji: '🇻🇦'),
  Country(name: 'Venezuela', alpha2Code: 'VE', alpha3Code: 'VEN', emoji: '🇻🇪'),
  Country(name: 'Vietnam', alpha2Code: 'VN', alpha3Code: 'VNM', emoji: '🇻🇳'),
  Country(name: 'Yemen', alpha2Code: 'YE', alpha3Code: 'YEM', emoji: '🇾🇪'),
  Country(name: 'Zambia', alpha2Code: 'ZM', alpha3Code: 'ZMB', emoji: '🇿🇲'),
  Country(name: 'Zimbabwe', alpha2Code: 'ZW', alpha3Code: 'ZWE', emoji: '🇿🇼'),
  Country(
  name: 'Côte d\'Ivoire',
  alpha2Code: 'CI',
  alpha3Code: 'CIV',
  emoji: '🇨🇮',
)

];
findCountryByCode(String code) {
  final normalizedCode = code.toUpperCase();
  return allCountries.firstWhere(
    (country) =>
        country.alpha2Code == normalizedCode || country.alpha3Code == normalizedCode,
    orElse: () => Country(name: '', alpha2Code: '', alpha3Code: '', emoji: ''),
  );
}
String getFlagByCode(String code) {
  final normalizedCode = code.toUpperCase();
  final country = allCountries.firstWhere(
    (country) =>
        country.alpha2Code == normalizedCode || country.alpha3Code == normalizedCode,
    orElse: () => Country(name: '', alpha2Code: '', alpha3Code: '', emoji: ''),
  );
  return country.emoji;
}
String getCountryNameByCode(String code) {
  final normalizedCode = code.toUpperCase();
  final country = allCountries.firstWhere(
    (country) =>
        country.alpha2Code == normalizedCode || country.alpha3Code == normalizedCode,
    orElse: () => Country(name: 'Inconnu', alpha2Code: '', alpha3Code: '', emoji: ''),
  );
  return country.name;
}
